### PR TITLE
patch to fix struct pack/unpack unicode error when python version < 2.7.7

### PR DESCRIPTION
**Pull request by air-upc**
patch to fix "TypeError: Struct() argument 1 must be string, not unicode" when python version < 2.7.7

### CODE REVIEW

**Comment by air-upc** [comment]
https://hg.python.org/cpython/raw-file/f89216059edf/Misc/NEWS #19099
We have got burned as py-amqp not works with python 2.7.5; will you make it compatible with python < 2.7.7? any solution is OK, not restricted to this pull request... @ask

**Comment by ask** [comment]
I just merged #93, which looks like fixes the same.

I do like this version though, as it's cleaner and only degrades performance on old Python versions,
so maybe we can use this instead.

**Comment by air-upc** [comment]
yeah, #93 fix the same problem, and I am so glad that we don't need to upgrade our python version in the near future as it's much exhausted.

**Comment by alanjds** [comment]
I did not knew that there are specific behaviours for different 2.7.X versions. It is a shame.

Anyway I do prefer this #96 over mine, as this concentrates the "compat" stuff in one place.

**Comment by ask** [comment]
Both of them are good really!  This version in #96 will add some overhead when using older Python versions.  I want pyamqp to be as fast as librabbitmq, and method calls/object lookups are exactly the sort of stuff I've been optimizing away in celery to gain better benchmarks (it adds up to quite a lot of message/s in the end).  If it was required on later Python 2.7 versions (our main deployment base), I would take #93.

I will find the time to merge both soon

**Comment by alanjds** [comment]
I was not aware of this performance target. Had you yet tested with "whole code" general optimisers/compilers like Numba, Nuitka or RPython yet? (just for me not try something already knew as a dead-end)

**Comment by franklingu** [comment]
So will this be in the latest release? I am using amqp==2.0.3 and clearly it is broken on Python 2.7.3 now.

I am still using Ubuntu 12.04 so I am using 2.7.3 now

**Comment by air-upc** [comment]
@ask  Sorry for haven't check this pull request for such a long time, but the coverage check result seems not good...

**Comment by yujiezeng** [comment]
Hello, I have been use this project, with python version of 2.7.3. I have got this error too, but I have used the patch file. I think the problem happens in _trasport.py_, which slao use _unpack_ from _struct_. So I changed it  and it works well. Maybe I think you should have some modification on _trasnport.py_

**Comment by air-upc** [comment]
@yujiezeng Modification to file `transport.py` lost when I rebase the pull request, what a terrible thing I have done. Thank you for the comment.

**Comment by AndyMan1** [comment]
FYI Pull #93 didn't include exceptions.py, so I'm seeing the same error from this line:
https://github.com/celery/py-amqp/blob/master/amqp/exceptions.py#L263

It looks like this pull request does include that fix.

I'm using py-amqp 2.1.0 and Python 2.7.5.

**Pull request closed without merging**
