### PR TITLE
Celery: Call drain_events on the connection before publishing

### PR DESCRIPTION
**Pull request by JelteF**
This is needed to capture out of memory messages for clients that only
publish. Otherwise `on_blocked` is never called.

### CODE REVIEW

**Comment by JelteF** [comment]
I'm not sure how to fix the coverage here. Can you let me know if this is necessary.

**Comment by auvipy** [comment]
add test if needed for the codes you added

**Comment by JelteF** [comment]
This would require to change settings in the rabbitmq backend (setting vm_memory_high_watermark to 0). With a quick look through the tests I cannot find something like that there.

**Comment by JelteF** [comment]
Based on what @ask said in #114 I think mock tests would be better here, to check that drain_events is called. I will try to add them in the near future.

**Comment by auvipy** [comment]
any updates?

**Comment by thedrow** [comment]
This can still make it to the release if tests are written.

**Comment by thedrow** [comment]
@JelteF Ping?

**Comment by JelteF** [comment]
Sorry for not responding to this anymore. We're moving away from celery at work and outside of work I don't have a lot of time to work on these things. If someone else would like to create a test for this that would be great, because I'm not sure when I will get around to it and the PR still fixes a big bug in the notification code.

**Comment by matusvalo** [comment]
I would like to finalize this functionality. Hopefully, soon I will add unittests and push it to this branch.

**Comment by thedrow** [comment]
#214 has completed the work on this PR.
Thank you for your contribution.

**Pull request closed without merging**
