### PR TITLE
Added integration tests

### PR DESCRIPTION
**Pull request by matusvalo**
This PR adds integration tests from py-amqp library. This tests verifies that proper callback is called when given method is received from network. This tests injects data at the lowest level possible in the `Transport.read_frame()` method. Integration of `Connection`, `Channel` and `AbstractChannel` classes is tested. Also the logic can be reused/extended to test more functionality of the library

### CODE REVIEW

**Comment by matusvalo** [comment]
Fails are caused by newer version of flake8. Previous version of flake8 is fine:
# flake8
./setup.py:48:1: E305 expected 2 blank lines after class or function definition, found 1
./setup.py:103:1: E305 expected 2 blank lines after class or function definition, found 1
./test.py:6:80: E501 line too long (96 > 79 characters)
./extra/update_comments_from_spec.py:75:1: E305 expected 2 blank lines after class or function definition, found 1

**Comment by auvipy** [comment]
Am going to fix the flake8 errors in a separate pr

**Comment by matusvalo** [comment]
@auvipy, I can move it to another location. Any preference/suggestion?

**Comment by matusvalo** [comment]
I have put some changes:
1. I have cleaned function mocking broker
2. I have added another integration test for connection handshake.
3. I have moved module with integration tests to separate directory

**Comment by matusvalo** [comment]
@auvipy I recently found out that randomly tests can fail. The problem is table datatype which can be serialized with different order of items. I will create a PR with fix of it.

**Comment by auvipy** [comment]
please do it

**Pull request merged**
