### PR TITLE
Version 5.0 - rebased version of #271

### PR DESCRIPTION
**Pull request by matusvalo**
This is updated version of PR #271 by @thedrow

### CODE REVIEW

**Comment by matusvalo** [comment]
Not sure if I can put changes directly to #271 hence I have created new PR.

**Comment by auvipy** [comment]
good job!

**Review by auvipy — APPROVED** [review]

**Comment by auvipy** [comment]
https://github.com/celery/py-amqp/tree/v2.6 will be maintenance branch and master will be python 3.6 only

**Comment by thedrow** [comment]
I guess we can work on this too as we have another release candidate anyway.

**Comment by auvipy** [comment]
ywa

**Pull request merged**
