### PR TITLE
document memoryview usage, minor frame_writer.write_frame refactor 

### PR DESCRIPTION
**Pull request by pawl**
I was looking at more py-amqp code and found a really interesting usage of `memoryview` in `frame_writer`'s `buffer_store`. I added some comments explaining why it's used.

I also moved some variables in `frame_writer`'s `write_frame` closer to where they're actually used. The `buffer_store` isn't used by `write_frame` when it ends up in the `if bigbody:` block, so I moved the code related to the `buffer_store` into the `else:`.

### CODE REVIEW

**Comment by pawl** [comment]
The integration tests failed to pull the rabbitmq image from dockerhub:
```
Step 1/6 : FROM rabbitmq:latest
Head "https://registry-1.docker.io/v2/library/rabbitmq/manifests/latest": received unexpected HTTP status: 503 Service Unavailable
Error: Process completed with exit code 1.
```

I think they'll pass if the tests are run again later.

**Review by auvipy — CHANGES_REQUESTED** [review]
please make sure unit & integration tests  are added or updated to avoid regression

**Comment by auvipy** [comment]
errors |  
-- | --
0 |  
code | "UNAUTHORIZED"
message | "authentication required"
detail |  
0 |  
Type | "repository"
Class | ""
Name | "library/rabbitmq"
Action | "pull"

**Review by auvipy — CHANGES_REQUESTED** [review]
the unit tests look good, can you please try to add some integration test as well? besides i want to read the links thoroughly and want others try the open patches so that the don't break

**Comment by pawl** [comment]
@auvipy I added that integration test here: https://github.com/celery/py-amqp/pull/384/commits/98b8bbc935537466032dc57fda373240d6185619

**Review by auvipy — APPROVED** [review]

**Pull request merged**
