### PR TITLE
add timeout to wait()

### PR DESCRIPTION
**Pull request by goir**
added timeout to wait()

### CODE REVIEW

**Comment by fake-name** [comment]
Is there any reason this hasn't been merged? I have an application that could really use it.

**Comment by pquentin** [comment]
@ask anything we can do to get this included? Thanks!

**Comment by ask** [comment]
Thanks! Merged into 1.4

**Comment by pquentin** [comment]
@ask awesome, thank you! can't wait for the next release. (I think the PR can be closed.)

**Comment by fake-name** [comment]
Now, if only this had happened 2 months ago (6 months after the request was opened!) so I didn't have to write a obnoxiously complicated work around.

**Comment by fake-name** [comment]
If this is merged, maybe close the request with a reference to the commit?

**Pull request closed without merging**
